name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main     # Change if your default branch is 'master' or other

permissions:
  contents: write  # <-- Add this line to allow pushing to branches

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fix permission for react-scripts
        run: chmod +x node_modules/.bin/react-scripts

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
